name: Build, Test and Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build_test_release:
    name: Build, Test and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2.2.4

      - name: Setup Node.js environment 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile --ignore-scripts

      - name: Run Build and Tests
        run: pnpm run build-test

      - name: Lint
        # Will run the step even if lint step failed
        if: success() || failure()
        run: pnpm lint

      - name: Version and release to npm
        # Don't run on PRs
        if: success() && github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: pnpm run release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
