name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: pnpm i --frozen-lockfile --no-frozen-lockfile

      - name: Run Build and Tests
        run: bun run build-test

      - name: Lint
        # Will run the step even if lint step failed
        if: success() || failure()
        run: bun lint
